name: gate_log
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.4.2+1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.2
  shimmer: ^2.0.0
  web_socket_channel: ^3.0.1
  infinite_scroll_pagination: ^4.0.0
  onestop_kit:
    git:
      url: https://github.com/swciitg/onestop_kit.git

  timeago: ^3.6.1
  screen_brightness: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
